// <auto-generated />
using System;
using DrowsinessDetectionServer.Datas;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrowsinessDetectionServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250426141719_DriverMonitorSession")]
    partial class DriverMonitorSession
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DrowsinessDetectionServer.Models.DatabaseModels.FaceData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Data1")
                        .HasColumnType("int");

                    b.Property<int>("Data2")
                        .HasColumnType("int");

                    b.Property<string>("Data3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Data4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DriverId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DriverId")
                        .IsUnique()
                        .HasFilter("[DriverId] IS NOT NULL");

                    b.ToTable("FaceDatas", (string)null);
                });

            modelBuilder.Entity("DrowsinessDetectionServer.Models.DatabaseModels.MonitorSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DriverId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.ToTable("MonitorSessions", (string)null);
                });

            modelBuilder.Entity("DrowsinessDetectionServer.Models.DatabaseModels.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("Latin1_General_CS_AS");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("UserName <> ''");

                    b.ToTable("Users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("DrowsinessDetectionServer.Models.DatabaseModels.Driver", b =>
                {
                    b.HasBaseType("DrowsinessDetectionServer.Models.DatabaseModels.User");

                    b.Property<long?>("SupervisorId")
                        .HasColumnType("bigint");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Drivers", (string)null);
                });

            modelBuilder.Entity("DrowsinessDetectionServer.Models.DatabaseModels.Supervisor", b =>
                {
                    b.HasBaseType("DrowsinessDetectionServer.Models.DatabaseModels.User");

                    b.ToTable("Supervisors", (string)null);
                });

            modelBuilder.Entity("DrowsinessDetectionServer.Models.DatabaseModels.FaceData", b =>
                {
                    b.HasOne("DrowsinessDetectionServer.Models.DatabaseModels.Driver", "Driver")
                        .WithOne("FaceData")
                        .HasForeignKey("DrowsinessDetectionServer.Models.DatabaseModels.FaceData", "DriverId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("DrowsinessDetectionServer.Models.DatabaseModels.MonitorSession", b =>
                {
                    b.HasOne("DrowsinessDetectionServer.Models.DatabaseModels.Driver", "Driver")
                        .WithMany("MonitorSessions")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("DrowsinessDetectionServer.Models.DatabaseModels.Driver", b =>
                {
                    b.HasOne("DrowsinessDetectionServer.Models.DatabaseModels.User", null)
                        .WithOne()
                        .HasForeignKey("DrowsinessDetectionServer.Models.DatabaseModels.Driver", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DrowsinessDetectionServer.Models.DatabaseModels.Supervisor", "Supervisor")
                        .WithMany("Drivers")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("DrowsinessDetectionServer.Models.DatabaseModels.Supervisor", b =>
                {
                    b.HasOne("DrowsinessDetectionServer.Models.DatabaseModels.User", null)
                        .WithOne()
                        .HasForeignKey("DrowsinessDetectionServer.Models.DatabaseModels.Supervisor", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DrowsinessDetectionServer.Models.DatabaseModels.Driver", b =>
                {
                    b.Navigation("FaceData");

                    b.Navigation("MonitorSessions");
                });

            modelBuilder.Entity("DrowsinessDetectionServer.Models.DatabaseModels.Supervisor", b =>
                {
                    b.Navigation("Drivers");
                });
#pragma warning restore 612, 618
        }
    }
}
